<link rel=stylesheet type="text/css" href="style.css">


<p>Hume. Hume thinks more like me than any writer of philosophy that I've ever read. Any rebuttal of his arguments is a rebuttal of my own. First to examine the ways that he's formalized arguments that I've thought of, made and believe.<br>
 Hume's fundamental argument is that everything humans know stems from the fact the experiences that we have had represent what will happen in the future. If I witness an event, and see the same circumstances set up in future, I should expect the same result. This continuity between past and future is essential for us to know how to interact with the world. I would call it a fundamental axiom of thought. The past is like the future. We have innumerable association of one cause with one effect. We generalize to the future and to similar situations. <br>
 Hume's sceptical premise is extremely important: that we do not believe things that we do not have experiences to justify, or things that violate rules that hold in every single other scenario. We also need evidence to smartly evaluate the truth or falsity of a claim. As evidence increases we increase the certainty of our belief. We do not believe in the absence of evidence. Evidence is experience in the world. <br>
 Hume spends a lot of space breaking down the arguments of those who believe in a supreme being. One novel argument that stood out to me is that if we look at creation as the effect of some force, and creation is the only metric we have to measure the magnitude of the creating force, we cannot suppose that the creator is greater or more perfect than the creation. So all of the imperfections we see in creation must be reflected in the creator, or at least we cannot assume that he surpasses them.<br>
 Hume derides the &lsquo;history' that comes out of barbaric nations that talks of miracles and gods, noting that the fool is quick to repeat and extemporize on tales that are heard, and that it is easy to convince them of fantastic tales. As more and more people believe the tales and they start being passed down by an ancestry, they start to be regarded as truth. But note the number of supernatural events that have happened in civilised societies, with witnesses who are capable of using reason and sound judgement. There are almost none. So we should distrust these stories whose evidence contradicts physical law (by definition of miracle) and which is insisted on by a mass of imaginative people refusing to think reasonably, but rather think with what they want to be true and with their emotion. <br>
 If a deity has created all people, then no person is responsible for his actions, but the deity who created him to be the kind of person who would act in such a way. <br>
 Hume finally demeans all fields that are not scientific or mathematical to a domain outside reason. This is surprisingly similar to a conclusion I came to that technical skill and mathematics are the only pure and true things that we know of, and that the power and certainty of these fields is a purer growth of human ability than anything else. <br>
 <br>
 <br>
 <br>
</p>