@extends('behavior-base')
@section('body')

<h1> Reading List </h1>
<p><a href="http://amzn.to/f00opN">Judgement in Managerial Decision Making (awesome)</a><br />
When faced with a decision, we all believe we&rsquo;re weighing the facts objectively and making rational, thoughtful decisions. In fact, science tells us that in situations requiring careful judgment, every individual is influenced by his or her own biases to some extent. Drawing on the very latest behavioral decision research this book examines judgment in a variety of managerial contexts and provides important insights that can help you make better managerial decisions.</p>
<p><a href="http://www.amazon.com/Influence-Practice-Robert-B-Cialdini/dp/0205609996?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Influence: The Psychology of Persuasion</a><br />Should be required Reading.</p>
<p><a href="http://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness/dp/014311526X?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Nudge: Improving Decisions about Health, Wealth, and Happiness</a>*&nbsp;<br />&#8220;This book is terrific. It will change the way you think, not only about the world around you and some of its bigger problems, but also about yourself.&#8221; -Michael Lewis</p>
<p><a href="http://www.amazon.com/Smart-People-Money-Mistakes-Correct/dp/1439163367?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Why Smart People Make Big Money Mistakes </a><br />Gary Belsky and Thomas Gilovich reveal the psychological forces &#8212; the patterns of thinking and decision making &#8212; behind seemingly irrational behavior. They explain why so many otherwise savvy people make foolish financial choices: why investors are too quick to sell winning stocks and too slow to sell losing shares, why home sellers leave money on the table and home buyers don&#8217;t get the biggest bang for their buck, why borrowers pay too much credit card interest and savers can&#8217;t sock away as much as they&#8217;d like, and why so many of us can&#8217;t control our spending.&nbsp;</p>
<p><a href="http://www.amazon.com/Breakdown-Will-Ainslie-George/dp/0521596947?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Breakdown of Will<br /></a>Ainslie argues that our responses to the threat of our own inconsistency determine the basic fabric of human culture. He suggests that individuals are more like populations of bargaining agents than like the hierarchical command structures envisaged by cognitive psychologists.</p>
<p><a href="http://www.amazon.com/Think-Twice-Harnessing-Power-Counterintuition/dp/1422176754?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Think Twice: Harnessing the Power of Counterintuition</a><br />In Think Twice, Michael Mauboussin shows you how to recognize-and avoid-common mental missteps, including: Misunderstanding cause-and-effect linkages; Aggregating micro-level behavior to predict macro-level behavior; Not considering enough alternative possibilities in making a decision; Relying too much on experts</p>
<p><a href="http://www.amazon.com/Identity-Economics-Identities-Shape-Well-Being/dp/0691146489?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Identity Economics: How Our Identities Shape Our Work, Wages, and Well-Being</a> <br />Monetary incentives are counter-productive in team environments that succeed in creating a culture of identity that fosters teamwork, where mission understanding and commitment are core to performance.</p>
<p><a href="http://www.amazon.com/Animal-Spirits-Psychology-Economy-Capitalism/dp/B0031DSW5S?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Animal Spirits: How Human Psychology Drives the Economy, and Why it Matters for Global Capitalism</a>*<br />Akerlof and Shiller reassert the necessity of an active government role in economic policymaking by recovering the idea of animal spirits, a term John Maynard Keynes used to describe the gloom and despondence that led to the Great Depression and the changing psychology that accompanied recovery. Like Keynes, Akerlof and Shiller know that managing these animal spirits requires the steady hand of government&#8211;simply allowing markets to work won&#8217;t do it.</p>
<p><a href="http://www.amazon.com/Predictably-Irrational-Hidden-Forces-Decisions/dp/006135323X?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Predictably Irrational: the Hidden Forces that Shape our Decisions</a>* <br />Ariely explains how expectations, emotions, social norms, and other invisible, seemingly illogical forces skew our reasoning abilities.  Not only do we make astonishingly simple mistakes every day, but we make the same types of mistakes. We consistently overpay, underestimate, and procrastinate. We fail to understand the profound effects of our emotions on what we want, and we overvalue what we already own.&nbsp;</p>
<p><a href="http://www.amazon.com/Rational-Decisions-Gorman-Lectures-Binmore/dp/0691130744?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Rational Decisions</a> <br />A concise, accessible, and expert view on Bayesian decision making.</p>
<p><a href="http://www.amazon.com/Sway-Irresistible-Pull-Irrational-Behavior/dp/0385530609?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">The Irresistible Pull of Irrational Behaviour</a> <br />What makes people act irrationally? This book explores the submerged mental drives that undermine rational action, from the desire to avoid loss to a failure to consider all the evidence or to perceive a person or situation beyond the initial impression and the reluctance to alter a plan that isn&#8217;t working.</p>
<p><a href="http://www.amazon.com/Advances-Behavioral-Economics-Roundtable/dp/0691116822?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Advances in Behavioral Economics<br /></a>Advances in Behavioral Economics will serve as the definitive one-volume resource for those who want to familiarize themselves with the new field or keep up-to-date with the latest developments.</p>
<p><a href="http://www.amazon.com/Behavioral-Game-Theory-Experiments-Interaction/dp/0691090394?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Behavioral GameTheory: Experiments in Strategic Interaction<br /></a>Colin Camerer, one of the field&#8217;s leading figures, uses psychological principles and hundreds of experiments to develop mathematical theories of reciprocity, limited strategizing, and learning, which help predict what real people and companies do in strategic situations. Unifying a wealth of information from ongoing studies in strategic behavior, he takes the experimental science of behavioral economics a major step forward.</p>
<p><a href="http://www.amazon.com/Behavioral-Economics-Applications-Peter-Diamond/dp/0691122849?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Behavioral Economics and its Applications</a> <br />In this volume, some of the world&#8217;s leading thinkers in behavioral economics and general economic theory make the case for a much greater use of behavioral ideas in six fields where these ideas have already proved useful but have not yet been fully incorporated&#8211;public economics, development, law and economics, health, wage determination, and organizational economics.</p>
<p><a href="http://www.amazon.com/Explaining-Social-Behavior-Bolts-Sciences/dp/0521777445?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Explaining Social Behavior: More Nuts and Bolts for the Social Sciences</a> <br />Jon Elster offers an overview of key explanatory mechanisms in the social sciences, relying on hundreds of examples and drawing on a large variety of sources-psychology, behavioral economics, biology, political science, historical writings, philosophy and fiction.</p>
<p><a href="http://www.amazon.com/Ulysses-Sirens-Rationality-Irrationality-Cambridge/dp/0521269849?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Ulysses and the Sirens: Studies in Rationality and Irrationality</a> <br />Elster critiques the notion of rationality in the economist&rsquo;s sense, as a faculty that is concerned with maximizing the satisfaction of agents&rsquo; present preferences. He contrasts this notion of locally maximizing rationality with what can be called globally maximizing rationality. This latter concept is perhaps best illustrated by those interesting situations where the best &ldquo;strategy&rdquo; is irrationality.</p>
<p><a href="http://www.amazon.com/Behavioural-Finance-William-Forbes/dp/0470028041?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Behavioural Finance</a> <br />William Forbes lays out the fundamentals of behavioral finance.</p>
<p><a href="http://www.amazon.com/Psychology-Investing-Prentice-Hall-Finance/dp/0136117031?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">The Psychology of Investing<br /></a>Traditional finance has focused on developing the tools that investors use to optimize expected return and risk. Understanding the motivations behind this behavior is extremely important when applying these financial tools.</p>
<p><a href="http://www.amazon.com/Beyond-Greed-Fear-Understanding-ebook/dp/B003ZHU1NQ?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Beyond Greed and Fear: Understanding Behavioral Finance and the Psychology of Investing </a><br />An entertaining, yet scholarly overview of the subject.</p>
<p><a href="http://www.amazon.com/Economics-Psychology-Promising-Cross-Disciplinary-Seminar/dp/0262514168?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Economics and Psychology: A Promising New Cross-Disciplinary Field</a> <br />The essays in Economics and Psychology take a broad view of the interface between these two disciplines, going beyond the usual focus on &#8220;behavioral economics.&#8221; As documented in this volume, the influence of psychology on economics has been responsible for a view of human behavior that calls into question the assumption of complete rationality (and raises the possibility of altruistic acts), the acceptance of experiments as a valid method of economic research, and the idea that utility or well-being can be measured.</p>
<p><a href="http://www.amazon.com/Irrational-Exuberance-Robert-J-Shiller/dp/0767923634?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Irrational Exuberence</a>* <br />A cult-classic at the time it was written.</p>
<p><a href="http://www.amazon.com/Introduction-Behavioral-Economics-Guide-Students/dp/0230532594?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">An Introduction to Behaviorial Economics<br /></a>&#8230;a superb introduction to the field of behavioral economics, suitable not only as an introductory text, but also as an entry-point for those desiring an engaging overview of the field.</p>
<p><a href="http://www.amazon.com/Moral-Markets-Critical-Values-Economy/dp/0691135231?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Moral Markets : the Critical Role of Values in the Economy<br /></a>This collection of essays provides an accessible guided tour of the frontier of current research in sociology, economics, biology and philosophy.</p>
<p><a href="http://www.amazon.com/Paradox-Choice-Why-More-Less/dp/0060005696?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">The Paradox of Choice: Why More Is Less</a><br />&#8230;we are faced with far too many choices on a daily basis, providing an illusion of a multitude of options when few honestly different ones actually exist.</p>
<p><a href="http://www.amazon.com/More-Than-You-Know-Unconventional/dp/0231143729?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">More Than You Know: Finding Financial Wisdom in Unconventional Places</a><br />A must read.</p>
<p><a href="http://www.amazon.com/Little-Book-Behavioral-Investing-Profits/dp/0470686022?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">The Little Book of Behavioral Investing: How not to be your own worst enemy</a> <br />&#8230;will enable you to identify and eliminate behavioral traits that can hinder your investment endeavors and show you how to go about achieving superior returns in the process.</p>
<p><a href="http://www.amazon.com/Morals-Markets-Evolutionary-Account-Modern/dp/0230600972?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Morals and Markets: an Evolutionary Account of the Modern World</a>&nbsp;<br />Economist and evolutionary game theorist Daniel Friedman demonstrates that our moral codes and our market systems-while often in conflict-are really devices evolved to achieve similar ends, and that society functions best when morals and markets are in balance with each other.</p>
<p><a href="http://www.amazon.com/Heuristics-Biases-Psychology-Intuitive-Judgment/dp/0521796792?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Heuristics and Biases: The Psychology of Intuitive Judgement<br /></a>When are people&#8217;s judgments prone to bias, and what is responsible for their biases? This book compiles psychologists&#8217; best attempts to answer these important questions.</p>
<p><a href="http://www.amazon.com/Moral-Sentiments-Material-Interests-Foundations/dp/0262572370?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Moral Sentiments and Material Interests: the Foundations of Cooperation in Economic Life<br /></a>&#8220;This book presents social science at its interdisciplinary best: an exhilarating mix of game theory, evolutionary biology, experimental economics, cultural anthropology, grammatology, and policy analysis. It will change our views of how biology and culture together determine social behavior.&#8221; &mdash;Daniel Kahneman</p>
<p><a href="http://www.amazon.com/Bounds-Reason-Unification-Behavioral-Sciences/dp/0691140529?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">The Bounds of Reason: Game Theory and the Unification of the Behavioral Sciences</a>&nbsp;<br />Game theory alone cannot fully explain human behavior and should instead complement other key concepts championed by the behavioral disciplines. Herbert Gintis shows that just as game theory without broader social theory is merely technical bravado, so social theory without game theory is a handicapped enterprise.</p>
<p><a href="http://www.amazon.com/Methodology-Experimental-Economics-Francesco-Guala/dp/0521618614?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">The Methodology of Experimental Economics</a>&nbsp;<br />This book provides the first comprehensive analysis and critical discussion of the methodology of experimental economics, written by a philosopher of science with expertise in the field.</p>
<p><a href="http://www.amazon.com/Handbook-Experimental-Economics-John-Kagel/dp/0691058970?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">The Handbook of Experimental Economics</a>&nbsp;<br />&#8230;presents a comprehensive critical survey of the results and methods of laboratory experiments in economics.</p>
<p><a href="http://www.amazon.com/Thinking-Deciding-Jonathan-Baron/dp/0521680433?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Thinking and Deciding</a><br />has established itself as the required text and important reference work for students and scholars of human cognition and rationality.</p>
<p><a href="http://www.amazon.com/Judgment-under-Uncertainty-Heuristics-Biases/dp/0521284147?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Judgement Under Uncertainty: Heuristics and Biases</a>&nbsp;<br />This volume is an important collection of papers, with relevance to anyone working in fields where decision-making is at the core. This is THE book.&nbsp;</p>
<p><a href="http://www.amazon.com/Choices-Values-Frames-Daniel-Kahneman/dp/0521627494?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Choices, Values, and Frames</a>&nbsp;<br />&#8230;presents an empirical and theoretical challenge to classical utility theory, offering prospect theory as an alternative framework. Extensions and applications to diverse economic phenomena and to studies of consumer behavior are discussed. The book also elaborates on framing effects and other demonstrations that preferences are constructed in context, and it develops new approaches to the standard view of choice-based utility.</p>
<p><a href="http://www.amazon.com/Construction-Preference-Sarah-Lichtenstein/dp/0521834287?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">The Construction of Preference<br /></a>When asked to make a decision, people often don&#8217;t really know what they want; they must construct their preferences &#8216;on the spot&#8217;. This book describes the concept of preference construction, tracing the blossoming of this idea within psychology, economics, marketing, law, and environmental policy.</p>
<p><a href="http://www.amazon.com/Behavioural-Finance-Insights-Irrational-Markets/dp/0470844876?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969" target="_blank">Behavioural Finance: Insights into Irrational Minds and Markets</a>&nbsp;<br />A good introduction.</p>
<p><a href="http://www.amazon.com/Value-Investing-Techniques-Intelligent-Investment/dp/0470683597?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Value Investing: Tools and Techniques for Intelligent Investment</a><br />why everything you learnt at business school is wrong</p>
<p><a href="http://www.amazon.com/History-Financial-Euphoria-Penguin-business/dp/0140238565?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">A Short History of Financial Euphoria</a><br />In this small but witty and well-crafted book, Galbraith chronicles the major speculative episodes, from the seventeenth-century tulipmania to the junk-bond follies of the eighties.</p>
<p><a href="http://www.amazon.com/Manias-Panics-Crashes-Financial-Investment/dp/0471467146?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Manias, Panics, and Crashes</a><br />&#8230;an engaging and entertaining account of the way that mismanagement of money and credit has led to financial explosions over the centuries. Covering such topics as the history and anatomy of crises, speculative manias, and the lender of last resort, this book puts the turbulence of the financial world in perspective.</p>
<p><a href="http://www.amazon.com/Devil-Take-Hindmost-Financial-Speculation/dp/0452281806?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Devil Take the Hindmost: A History of Financial Speculation</a><br />A must read.</p>
<p><a href="http://www.amazon.com/Animal-Spirits-Psychology-Capitalism-Audiobook/dp/B004CZH0VG?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Animal Spirits: How Human Psychology Drives the Economy, and Why It Matters for Global Capitalism</a><br />Akerlof and Shiller reassert the necessity of an active government role in economic policymaking by recovering the idea of animal spirits, a term John Maynard Keynes used to describe the gloom and despondence that led to the Great Depression and the changing psychology that accompanied recovery. Like Keynes, Akerlof and Shiller know that managing these animal spirits requires the steady hand of government&#8211;simply allowing markets to work won&#8217;t do it. In rebuilding the case for a more robust, behaviorally informed Keynesianism, they detail the most pervasive effects of animal spirits in contemporary economic life&#8211;such as confidence, fear, bad faith, corruption, a concern for fairness, and the stories we tell ourselves about our economic fortunes&#8211;and show how Reaganomics, Thatcherism, and the rational expectations revolution failed to account for them.</p>
<p><a href="http://www.amazon.com/Discover-Your-Inner-Economist-Incentives/dp/B0013VZI84?ie=UTF8&amp;tag=farnamstreet-20&amp;link_code=btl&amp;camp=213689&amp;creative=392969">Discover Your Inner Economist </a><br />An engaging narrator, Cowen offers idiosyncratic strategies for appreciating museum art, for building family trust and cooperation, for writing a personal ad, for reading classic novels that seem boring on first inspection, for surviving torture, for properly practicing self-deception and for most effectively giving to beggars in Calcutta.</p>
<p><strong>Additions to the list in 2011</strong></p>
<p><a href="http://www.amazon.com/gp/product/0374275637/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399373&#038;creativeASIN=0374275637">Thinking, Fast and Slow</a><br />
Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. Kahneman exposes the extraordinary capabilities—and also the faults and biases—of fast thinking, and reveals the pervasive influence of intuitive impressions on our thoughts and behavior. The impact of loss aversion and overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the challenges of properly framing risks at work and at home, the profound effect of cognitive biases on everything from playing the stock market to planning the next vacation—each of these can be understood only by knowing how the two systems work together to shape our judgments and decisions.</p>
<p><a href="http://www.amazon.com/gp/product/0385531680/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399373&#038;creativeASIN=0385531680">Everything Is Obvious: *Once You Know the Answer</a><br />
&#8220;Every once in a while, a book comes along that forces us to re-examine what we know and how we know it. This is one of those books. And while it is not always pleasurable to realize the many ways in which we are wrong, it is useful to figure out the cases where our intuitions fail us.&#8221;—Dan Ariely</p>
<p><a href="http://www.amazon.com/gp/product/0809078813/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399369&#038;creativeASIN=0809078813">Priceless: The Myth of Fair Value (and How to Take Advantage of It)</a><br />
Poundstone dives into the latest psychological findings to investigate how and why prices are allocated.</p>
<p><a href="http://www.amazon.com/gp/product/0674013824/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399369&#038;creativeASIN=0674013824">Strangers to Ourselves: Discovering the Adaptive Unconscious</a><br />
Wilson attempts to explain why there&#8217;s so much about ourselves that we fail to understand, which can lead to misdirected anger. </p>
<p><a href="http://www.amazon.com/gp/product/184916424X/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399373&#038;creativeASIN=184916424X">Born Liars: Why We Can&#8217;t Live Without Deceit</a><br />
&#8220;&#8230; a lively, engaging read that also makes a bold argument about the role of lying in our lives&#8221;</p>
<p><a href="http://www.amazon.com/gp/product/0521662133/ref=as_li_tf_tl?ie=UTF8&#038;tag=farnamstreet-20&#038;linkCode=as2&#038;camp=217145&#038;creative=399373&#038;creativeASIN=0521662133">Ulysses Unbound: Studies in Rationality, Precommitment, and Constraints</a><br />
This provocative book argues that, very often, people may benefit from being constrained in their options or from being ignorant.</p>
@stop